name: test-workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      
      - name: Run Mod 
        run: go mod tidy

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      
      - name: Run Mod 
        run: go mod tidy

      - name: Build and deploy
        run: |
          go build -o /cmd/main/main.go

      -  run: ./main
